require("user.options")
require("user.colorscheme")
require("user.colorizer")
require("user.keymaps")
require("user.plugins")
-- require("user.impatient")
require("user.cmp")
require("user.lsp")
require("user.symbols_outline")
require("user.nvim_lightbulb")
require("user.inc_rename")
require("user.telescope")
require("user.project")
-- require("user.transparent")
require("user.treesitter")
require("user.lsp_signature")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvimtree_cfg")
require("user.bufferline")
require("user.scope")
require("user.toggleterm")
require("user.lualine-primary")
require("user.alpha")
require("user.vimtex")
