# ==========================
# ===  General settings  ===
# ==========================
set default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc" # without this line, nvim bg will be overwritten
# Change prefix key to C-Space, easier to type, same to "screen"
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# source config file
bind R source-file ~/.config/tmux/tmux.conf; display "Reloaded config"


# panes
set mouse

# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'dracula/tmux'

# Dracula config
# ----------------------------------------------------
set -g @dracula-show-powerline true

# default terminal to alacritty
set default-terminal alacritty

# default shell to fish
set default-command /usr/bin/fish
set default-shell /usr/bin/fish

run '~/.tmux/plugins/tpm/tpm'
